apiVersion: v1
kind: Service
metadata:
  name: productpage
  namespace: mesh-demo
  labels:
    app: productpage
spec:
  selector:
    app: productpage
  ports:
  - name: http
    port: 9080
    targetPort: 9080
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: details
  namespace: mesh-demo
  labels:
    app: details
spec:
  selector:
    app: details
  ports:
  - name: http
    port: 9080
    targetPort: 9080
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: reviews
  namespace: mesh-demo
  labels:
    app: reviews
spec:
  selector:
    app: reviews
  ports:
  - name: http
    port: 9080
    targetPort: 9080
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: mesh-demo
  labels:
    app: ratings
spec:
  selector:
    app: ratings
  ports:
  - name: http
    port: 9080
    targetPort: 9080
    protocol: TCP
  type: ClusterIP

