# Core hello service definition
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: mesh-demo
  labels:
    app: hello
    version: v1
spec:
  selector:
    app: hello
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP