apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
  namespace: mesh-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
        - name: curl
          image: curlimages/curl:8.9.1
          command: ["sleep", "infinity"]
          # No ports
          # Just a shell with curl
          # It will also get a sidecar
